#!/bin/bash

# ASCII Art
echo "  _______          _         _______ _          _ _ "
echo " |__   __|        (_)       |__   __| |        | | |"
echo "    | | ___  _ __  _ _ __       | |  | |__   ___| | |"
echo "    | |/ _ \| '_ \| | '_ \      | |  | '_ \ / _ \ | |"
echo "    | | (_) | | | | | |_) |     | |  | | | |  __/ | |"
echo "    |_|\___/|_| |_|_| .__/      |_|  |_| |_|\___|_|_|"
echo "                    | |                              "
echo "                    |_|                              "
echo "-----------------------------------------------------"
echo "            Offensive Security Terminal
                    Author: Richard Schmidt                "
echo "-----------------------------------------------------"

# Get the directory of the script
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Path for the settings.conf file
conf_file="$script_dir/settings.conf"
bashrc_file="$script_dir/.bashrc"

# Ensure settings.conf exists
if [ ! -f "$conf_file" ]; then
  touch "$conf_file"
fi

# Create an associative array to keep track of variables
declare -A added_variables

# Function to add a variable to the settings.conf file
add_variable() {
  local variable_name="$1"
  local variable_value="$2"

  # Remove existing variable if it exists
  sed -i "/^$variable_name=/d" "$conf_file"

  # Add the new variable
  echo "$variable_name=$variable_value" >> "$conf_file"
  added_variables["$variable_name"]=1
  echo "Variable name and value added: $variable_name"
}

# Input for Target IP
read -p "Enter Target IP (optional): " target_ip
if [[ -n $target_ip && ! $target_ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "Invalid IP address format"
  exit 1
fi

# Input for Target URL
read -p "Enter Target URL (optional): " target_url
if [[ -n $target_url && ! $target_url =~ ^https?:// ]]; then
  echo "Invalid URL format"
  exit 1
fi

# Add IP and URL to settings.conf if they are provided
if [[ -n $target_ip ]]; then
  add_variable "IP" "$target_ip"
fi
if [[ -n $target_url ]]; then
  add_variable "URL" "$target_url"
fi

# Loop to input Wordlist Paths and write to the configuration file
while true; do
  read -p "Enter Wordlist Variable Name (or 'q' to quit): " variable_name
  if [[ $variable_name == 'q' ]]; then
    break
  fi

  read -p "Enter Wordlist Path: " wordlist_path
  if [ -f "$wordlist_path" ]; then
    add_variable "$variable_name" "$wordlist_path"
  else
    echo "File does not exist at the specified path: $wordlist_path"
  fi
done

# Create and populate .bashrc with environment variable assignments
{
  echo "# Automatically generated by the setup script"
  echo "conf_file=\"$conf_file\""
  while read -r line; do
    echo "export $line"
  done < "$conf_file"
} > "$bashrc_file"

echo "Settings updated successfully and added to $bashrc_file!"
echo "You can now use 'ping \$IP' or 'ping \$URL', and '\$wordlistN' to view the wordlists."
